/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/trades": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 교환/양도 목록 조회
     * @description 필터링 옵션으로 교환/양도 목록을 조회합니다
     */
    get: operations["getTrades"];
    put?: never;
    /**
     * 교환/양도 등록
     * @description 새로운 교환/양도를 등록합니다. 교환은 1개, 양도는 1개 이상 가능합니다.
     */
    post: operations["createTrade"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trades/{tradeId}/requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 교환/양도 신청
     * @description 등록된 교환/양도에 신청합니다 (EXCHANGE 타입의 경우 본인의 티켓 ID 필요)
     */
    post: operations["createTradeRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reservations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 예매 생성
     * @description 좌석을 예매합니다.
     *     - 로그인 사용자만 가능
     *     - 좌석 상태가 AVAILABLE일 때만 HOLD 후 예매 생성
     *     - Redis 분산락 기반 동시성 처리
     */
    post: operations["createReservation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reservations/{reservationId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 예매 확정 (결제 완료)
     * @description 결제 성공 시 예매를 확정합니다.
     *     - 좌석은 SOLD 상태로 변경됩니다.
     *     - 취소된 예매는 확정할 수 없습니다.
     */
    post: operations["completeReservation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances/{performanceId}/schedules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSchedules"];
    put?: never;
    post: operations["createSchedule"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances/{performanceId}/lottery/entry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 추첨 응모 생성
     * @description 공연에 대해 추첨 예매 응모를 생성 - 로그인 사용자만 가능
     */
    post: operations["registerLotteryEntry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/payments/prepare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["prepare"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/mypage/account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getRefundAccount"];
    put?: never;
    post: operations["setRefunAccount"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/members/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/email/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 인증 코드 검증
     * @description 발송된 인증 코드 검증
     */
    post: operations["verifyCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/email/verification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 인증 코드 발송
     * @description 입력한 이메일로 6자리 인증 코드 발송
     */
    post: operations["sendVerificationCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/email/check-duplicate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일 중복 확인 */
    post: operations["checkDuplicate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/reissue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["reissue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/venues/{venueId}/sections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 공연장 구역 정보 생성
     * @description 공연장의 구역 정보를 등록
     */
    post: operations["createSection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/venues/{venueId}/seats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 좌석 생성
     * @description 공연장의 좌석을 등록
     */
    post: operations["createSeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trades/{tradeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 교환/양도 상세 조회
     * @description 특정 교환/양도 건의 상세 정보를 조회합니다
     */
    get: operations["getTrade"];
    put?: never;
    post?: never;
    /**
     * 교환/양도 삭제
     * @description 등록한 교환/양도를 삭제합니다
     */
    delete: operations["deleteTrade"];
    options?: never;
    head?: never;
    /**
     * 교환/양도 수정
     * @description 등록한 교환/양도 정보를 수정합니다
     */
    patch: operations["updateTrade"];
    trace?: never;
  };
  "/api/trade-requests/{tradeRequestId}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 교환/양도 신청 거절
     * @description 교환/양도 신청을 거절합니다
     */
    patch: operations["rejectTradeRequest"];
    trace?: never;
  };
  "/api/trade-requests/{tradeRequestId}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 교환/양도 신청 수락 (티켓 소유권 이전)
     * @description 교환/양도 신청을 수락하고 티켓 소유권을 이전합니다.
     *
     *     - TRANSFER: 신청자에게 티켓 양도
     *     - EXCHANGE: 서로의 티켓을 교환
     */
    patch: operations["acceptTradeRequest"];
    trace?: never;
  };
  "/api/mypage/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["changePassword"];
    trace?: never;
  };
  "/api/venues/{venueId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getVenue"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trade-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 교환/양도 신청 목록 조회
     * @description 특정 거래에 대한 신청 목록 또는 내가 신청한 목록을 조회합니다 (둘 중 하나는 필수)
     */
    get: operations["getTradeRequests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trade-requests/{tradeRequestId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 교환/양도 신청 상세 조회
     * @description 특정 교환/양도 신청의 상세 정보를 조회합니다
     */
    get: operations["getTradeRequest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tickets/my": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 티켓 목록 조회
     * @description 본인이 소유한 티켓 목록을 조회합니다
     */
    get: operations["getMyTickets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schedules/{scheduleId}/seats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 회차별 좌석 조회
     * @description 특정 회차의 좌석 목록을 조회합니다.
     *     - status 미지정 시 전체 조회
     *     - status 지정 시 해당 상태 좌석만 조회
     */
    get: operations["getScheduleSeats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schedules/ticketing/schedules/{scheduleId}/seats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 티켓팅 전용 좌석 조회
     * @description 티켓팅 화면에서 사용되는 AVAILABLE 상태 좌석 조회 API
     */
    get: operations["getAvailableSeatsForTicketing"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reservations/{reservationId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 예매 상세 조회
     * @description 예매 ID로 예매 상세 정보를 조회합니다.
     *     - 공연 / 회차 / 좌석 정보 포함
     *     - 예매 상세 화면용 API
     */
    get: operations["getReservationDetail"];
    put?: never;
    post?: never;
    /**
     * 예매 취소
     * @description 예매를 취소합니다.
     *     - 이미 결제 완료된 예매는 취소 불가
     *     - 취소 시 좌석 상태는 AVAILABLE로 복구됩니다.
     */
    delete: operations["cancelReservation"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reservations/{reservationId}/simple": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 예매 단건 조회
     * @description 예매 ID로 예매 기본 정보를 조회합니다.
     *     - 로그인 사용자 본인 예매만 조회 가능
     *     - 결제/취소/확정 전 상태 확인용 API
     */
    get: operations["getReservation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reservations/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 예매 목록 조회 (디테일)
     * @description 로그인한 사용자의 모든 예매 내역을 조회합니다.
     *     - 공연 / 회차 / 좌석 정보 포함
     *     - QueryDSL 기반 조회 전용 API
     */
    get: operations["getMyReservationsDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reservations/me/simple": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 예매 목록 조회 (간단)
     * @description 로그인한 사용자의 예매 목록을 조회합니다.
     *     - 예매 기본 정보만 반환
     *     - 목록 요약 또는 내부 로직용
     */
    get: operations["getMyReservations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPerformances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances/{performanceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPerformance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances/{performanceId}/schedules/{scheduleId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSchedule"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances/{performanceId}/lottery/section": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 구역별 좌석 배치 조회
     * @description 공연 ID로 추첨 예매에 사용되는 구역별 좌석 배치 정보를 조회
     */
    get: operations["getSeatLayout"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/performances/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["searchPerformances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/mypage/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMyInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/mypage/withdraw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["withdrawUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/mypage/lottery/entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 응모 내역 조회
     * @description 내가 응모한 공연 내역을 조회 - 내 것만 조회가능
     */
    get: operations["getMyLotteryEntry"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/banks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBankList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateTradeReq: {
      ticketIds: number[];
      /** @enum {string} */
      type: "EXCHANGE" | "TRANSFER";
      /** Format: int32 */
      price?: number;
    };
    BaseResponseListCreateTradeRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["CreateTradeRes"][];
    };
    CreateTradeRes: {
      /** Format: int64 */
      tradeId?: number;
      /** @enum {string} */
      type?: "EXCHANGE" | "TRANSFER";
      /** @enum {string} */
      status?: "ACTIVE" | "COMPLETED" | "CANCELLED";
      section?: string;
      row?: string;
      seatNumber?: string;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      price?: number;
    };
    CreateTradeRequestReq: {
      /** Format: int64 */
      requesterTicketId: number;
    };
    BaseResponseTradeRequestRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["TradeRequestRes"];
    };
    TradeRequestRes: {
      /** Format: int64 */
      tradeRequestId?: number;
      /** Format: int64 */
      tradeId?: number;
      /** Format: int64 */
      requesterId?: number;
      /** Format: int64 */
      requesterTicketId?: number;
      /** @enum {string} */
      status?: "PENDING" | "ACCEPTED" | "REJECTED";
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      modifiedAt?: string;
    };
    ReservationReq: {
      /** Format: int64 */
      scheduleId: number;
      /** Format: int64 */
      seatIds: number[];
    };
    BaseResponseReservationDetailRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ReservationDetailRes"];
    };
    PerformanceInfo: {
      /** Format: int64 */
      performanceId?: number;
      /** Format: int64 */
      performanceScheduleId?: number;
      title?: string;
      category?: string;
      /** Format: date-time */
      startDate?: string;
      /** Format: date-time */
      startAt?: string;
    };
    ReservationDetailRes: {
      /** Format: int64 */
      reservationId?: number;
      status?: string;
      performance?: components["schemas"]["PerformanceInfo"];
      seat?: components["schemas"]["SeatInfo"];
    };
    SeatInfo: {
      /** Format: int64 */
      seatId?: number;
      /** Format: int64 */
      sectionId?: number;
      sectionName?: string;
      rowLabel?: string;
      /** Format: int32 */
      seatNumber?: number;
    };
    BaseResponseVoid: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: unknown;
    };
    PerformanceScheduleCreateReq: {
      /** Format: date-time */
      startAt: string;
      /** Format: int32 */
      roundNo: number;
      /** @enum {string} */
      bookingType: "FIRST_COME" | "PRERESERVE" | "LOTTERY";
      /** Format: date-time */
      bookingOpenAt: string;
      /** Format: date-time */
      bookingCloseAt?: string;
    };
    BaseResponsePerformanceScheduleCreateRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PerformanceScheduleCreateRes"];
    };
    PerformanceScheduleCreateRes: {
      /** Format: int64 */
      performanceScheduleId?: number;
      /** Format: int64 */
      performanceId?: number;
      /** Format: date-time */
      startAt?: string;
      /** Format: int32 */
      roundNo?: number;
      /** @enum {string} */
      bookingType?: "FIRST_COME" | "PRERESERVE" | "LOTTERY";
      /** Format: date-time */
      bookingOpenAt?: string;
      /** Format: date-time */
      bookingCloseAt?: string;
    };
    RegisterLotteryEntryReq: {
      /** Format: int64 */
      scheduleId: number;
      grade: string;
      /** Format: int32 */
      quantity: number;
    };
    BaseResponseLotteryEntryInfo: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["LotteryEntryInfo"];
    };
    LotteryEntryInfo: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      memberId?: number;
      /** Format: int64 */
      performanceId?: number;
      /** Format: int64 */
      scheduleId?: number;
      grade?: string;
      /** Format: int32 */
      quantity?: number;
      status?: string;
    };
    PaymentPrepareReq: {
      /** @enum {string} */
      domainType: "RESERVATION" | "LOTTERY" | "TRADE";
      /** Format: int64 */
      domainId: number;
      /** @enum {string} */
      paymentMethod: "CARD" | "EASY_PAY" | "VIRTUAL_ACCOUNT";
    };
    BaseResponsePaymentPrepareRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PaymentPrepareRes"];
    };
    PaymentPrepareRes: {
      /** Format: int64 */
      paymentId?: number;
      orderId?: string;
      /** Format: int64 */
      amount?: number;
      /** @enum {string} */
      status?:
        | "READY"
        | "WAITING_FOR_DEPOSIT"
        | "DONE"
        | "FAILED"
        | "CANCELED"
        | "EXPIRED";
      /** Format: date-time */
      expiresAt?: string;
    };
    RefundAccountReq: {
      /** @enum {string} */
      bankCode:
        | "004"
        | "023"
        | "027"
        | "081"
        | "088"
        | "089"
        | "090"
        | "092"
        | "020"
        | "003"
        | "011"
        | "045"
        | "048"
        | "071";
      accountNumber: string;
      holderName: string;
    };
    SignupReq: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
      phone: string;
      /** Format: date */
      birth: string;
    };
    BaseResponseLong: {
      /** Format: int32 */
      code?: number;
      message?: string;
      /** Format: int64 */
      data?: number;
    };
    VerifyCodeReq: {
      /** Format: email */
      email: string;
      code: string;
    };
    SenderVerificationReq: {
      /** Format: email */
      email: string;
    };
    CheckDuplicateReq: {
      /** Format: email */
      email: string;
    };
    BaseResponseCheckDuplicateRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["CheckDuplicateRes"];
    };
    CheckDuplicateRes: {
      available?: boolean;
    };
    TokenReissueReq: {
      accessToken: string;
      refreshToken: string;
    };
    BaseResponseTokenInfo: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["TokenInfo"];
    };
    TokenInfo: {
      grantType?: string;
      accessToken?: string;
    };
    LoginReq: {
      /** Format: email */
      email: string;
      password: string;
    };
    CreateSectionReq: {
      sectionName: string;
    };
    BaseResponseCreateSectionRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["CreateSectionRes"];
    };
    CreateSectionRes: {
      /** Format: int64 */
      sectionId?: number;
      /** Format: int64 */
      venueId?: number;
      sectionName?: string;
    };
    CreateSeatReq: {
      /** Format: int64 */
      sectionId: number;
      rowLabel: string;
      /** Format: int32 */
      seatNumber: number;
    };
    BaseResponseCreateSeatRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["CreateSeatRes"];
    };
    CreateSeatRes: {
      /** Format: int64 */
      seatId?: number;
      /** Format: int64 */
      venueId?: number;
      /** Format: int64 */
      sectionId?: number;
      sectionName?: string;
      rowLabel?: string;
      /** Format: int32 */
      seatNumber?: number;
    };
    UpdateTradeReq: {
      /** Format: int32 */
      price: number;
    };
    PasswordChangeReq: {
      currentPassword: string;
      newPassword: string;
    };
    BaseResponseVenueRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["VenueRes"];
    };
    VenueRes: {
      /** Format: int64 */
      venueId?: number;
      name?: string;
    };
    BaseResponsePageTradeRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PageTradeRes"];
    };
    PageTradeRes: {
      /** Format: int32 */
      totalPages?: number;
      /** Format: int64 */
      totalElements?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["TradeRes"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    TradeRes: {
      /** Format: int64 */
      tradeId?: number;
      /** Format: int64 */
      memberId?: number;
      /** Format: int64 */
      performanceId?: number;
      /** Format: int64 */
      scheduleId?: number;
      /** Format: int64 */
      ticketId?: number;
      /** @enum {string} */
      type?: "EXCHANGE" | "TRANSFER";
      /** @enum {string} */
      status?: "ACTIVE" | "COMPLETED" | "CANCELLED";
      /** Format: int32 */
      price?: number;
      /** Format: int32 */
      totalCount?: number;
      section?: string;
      row?: string;
      seatNumber?: string;
      performanceTitle?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    BaseResponseTradeRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["TradeRes"];
    };
    BaseResponseListTradeRequestRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["TradeRequestRes"][];
    };
    BaseResponseListTicketRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["TicketRes"][];
    };
    TicketRes: {
      /** Format: int64 */
      ticketId?: number;
      /** Format: int64 */
      reservationId?: number;
      /** Format: int64 */
      seatId?: number;
      /** @enum {string} */
      acquisitionType?: "RESERVATION" | "TRANSFER" | "EXCHANGE";
      /** @enum {string} */
      status?:
        | "ISSUED"
        | "USED"
        | "CANCELED"
        | "EXCHANGED"
        | "TRANSFERRED"
        | "EXPIRED";
      sectionName?: string;
      rowLabel?: string;
      /** Format: int32 */
      seatNumber?: number;
      /** Format: int64 */
      performanceId?: number;
    };
    BaseResponseListScheduleSeatViewRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ScheduleSeatViewRes"][];
    };
    ScheduleSeatViewRes: {
      /** Format: int64 */
      scheduleSeatId?: number;
      /** Format: int64 */
      seatId?: number;
      sectionName?: string;
      rowLabel?: string;
      /** Format: int32 */
      seatNumber?: number;
      /** @enum {string} */
      status?: "AVAILABLE" | "HOLD" | "SOLD";
      grade?: string;
      /** Format: int32 */
      price?: number;
    };
    BaseResponseReservationRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ReservationRes"];
    };
    ReservationRes: {
      /** Format: int64 */
      reservationId?: number;
      /** Format: int64 */
      memberId?: number;
      /** Format: int64 */
      scheduleId?: number;
      /** Format: int64 */
      seatId?: number;
      reservationStatus?: string;
    };
    BaseResponseListReservationDetailRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ReservationDetailRes"][];
    };
    BaseResponseListReservationRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ReservationRes"][];
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    BaseResponsePagePerformanceListRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PagePerformanceListRes"];
    };
    PagePerformanceListRes: {
      /** Format: int32 */
      totalPages?: number;
      /** Format: int64 */
      totalElements?: number;
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["PerformanceListRes"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PerformanceListRes: {
      /** Format: int64 */
      performanceId?: number;
      title?: string;
      category?: string;
      posterUrl?: string;
      venueName?: string;
      bookingType?: "LOTTERY" | "FIRST_COME" | "PRERESERVE";
      /** Format: date-time */
      startDate?: string;
      /** Format: date-time */
      endDate?: string;
    };
    BaseResponsePerformanceDetailRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PerformanceDetailRes"];
    };
    PerformanceDetailRes: {
      /** Format: int64 */
      performanceId?: number;
      title?: string;
      category?: string;
      posterUrl?: string;
      description?: string;
      /** Format: date-time */
      startDate?: string;
      /** Format: date-time */
      endDate?: string;
      /** @enum {string} */
      status?: "ON_SALE" | "ENDED";
      venue?: components["schemas"]["VenueSummary"];
    };
    VenueSummary: {
      /** Format: int64 */
      venueId?: number;
      name?: string;
    };
    BaseResponseListPerformanceScheduleListRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PerformanceScheduleListRes"][];
    };
    PerformanceScheduleListRes: {
      /** Format: int64 */
      performanceScheduleId?: number;
      /** Format: date-time */
      startAt?: string;
      /** Format: int32 */
      roundNo?: number;
      /** @enum {string} */
      bookingType?: "FIRST_COME" | "PRERESERVE" | "LOTTERY";
      /** Format: date-time */
      bookingOpenAt?: string;
      /** Format: date-time */
      bookingCloseAt?: string;
    };
    BaseResponsePerformanceScheduleDetailRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["PerformanceScheduleDetailRes"];
    };
    PerformanceScheduleDetailRes: {
      /** Format: int64 */
      performanceScheduleId?: number;
      /** @enum {string} */
      bookingType?: "FIRST_COME" | "PRERESERVE" | "LOTTERY";
      /** Format: date-time */
      bookingOpenAt?: string;
      /** Format: date-time */
      bookingCloseAt?: string;
    };
    BaseResponseListSectionLayoutRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["SectionLayoutRes"][];
    };
    GradeInfo: {
      /** @enum {string} */
      grade?:
        | "STANDARD"
        | "VIP"
        | "ROYAL"
        | "SUPERIOR"
        | "A"
        | "B"
        | "RESTRICTED_VIEW";
      rows?: string[];
    };
    SectionLayoutRes: {
      sectionName?: string;
      grades?: components["schemas"]["GradeInfo"][];
    };
    BaseResponseMyInfoRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["MyInfoRes"];
    };
    MyInfoRes: {
      /** Format: int64 */
      memberId?: number;
      email?: string;
      name?: string;
      phone?: string;
      /** Format: date */
      birth?: string;
      isEmailVerified?: boolean;
      isIdentityVerified?: boolean;
    };
    AppliedLotteryInfo: {
      /** Format: int64 */
      lotteryEntryId?: number;
      title?: string;
      /** Format: date-time */
      startAt?: string;
      /** Format: int32 */
      roundNo?: number;
      /** @enum {string} */
      gradeType?:
        | "STANDARD"
        | "VIP"
        | "ROYAL"
        | "SUPERIOR"
        | "A"
        | "B"
        | "RESTRICTED_VIEW";
      /** Format: int32 */
      quantity?: number;
      /** @enum {string} */
      status?: "APPLIED" | "WIN" | "LOSE";
    };
    BaseResponseListAppliedLotteryInfo: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["AppliedLotteryInfo"][];
    };
    BaseResponseRefundAccountRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["RefundAccountRes"];
    };
    RefundAccountRes: {
      bankCode?: string;
      bankName?: string;
      accountNumber?: string;
      holderName?: string;
    };
    BankRes: {
      code?: string;
      name?: string;
    };
    BaseResponseListBankRes: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["BankRes"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getTrades: {
    parameters: {
      query?: {
        /** @description 거래 타입 (TRANSFER: 양도, EXCHANGE: 교환) */
        type?: "EXCHANGE" | "TRANSFER";
        /** @description 거래 상태 (ACTIVE: 진행중, COMPLETED: 완료, CANCELED: 취소) */
        status?: "ACTIVE" | "COMPLETED" | "CANCELLED";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePageTradeRes"];
        };
      };
    };
  };
  createTrade: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTradeReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListCreateTradeRes"];
        };
      };
    };
  };
  createTradeRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 거래 ID
         * @example 1
         */
        tradeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTradeRequestReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseTradeRequestRes"];
        };
      };
    };
  };
  createReservation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 예매 요청 정보 (scheduleId, seatId) */
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReservationReq"];
      };
    };
    responses: {
      /** @description 예매 생성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationDetailRes"];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationDetailRes"];
        };
      };
      /** @description 이미 HOLD 또는 SOLD된 좌석 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationDetailRes"];
        };
      };
    };
  };
  completeReservation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 예매 ID
         * @example 1
         */
        reservationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 확정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
      /** @description 본인의 예매가 아님 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
      /** @description 예매 정보 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
      /** @description 취소된 예매는 확정 불가 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  getSchedules: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        performanceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListPerformanceScheduleListRes"];
        };
      };
    };
  };
  createSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        performanceId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PerformanceScheduleCreateReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePerformanceScheduleCreateRes"];
        };
      };
    };
  };
  registerLotteryEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        performanceId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterLotteryEntryReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseLotteryEntryInfo"];
        };
      };
    };
  };
  prepare: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentPrepareReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePaymentPrepareRes"];
        };
      };
    };
  };
  getRefundAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseRefundAccountRes"];
        };
      };
    };
  };
  setRefunAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefundAccountReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseLong"];
        };
      };
    };
  };
  verifyCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyCodeReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  sendVerificationCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SenderVerificationReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  checkDuplicate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckDuplicateReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseCheckDuplicateRes"];
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refreshToken?: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TokenReissueReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseTokenInfo"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseTokenInfo"];
        };
      };
    };
  };
  createSection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        venueId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSectionReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseCreateSectionRes"];
        };
      };
    };
  };
  createSeat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 공연장 ID
         * @example 1
         */
        venueId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSeatReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseCreateSeatRes"];
        };
      };
    };
  };
  getTrade: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 거래 ID
         * @example 1
         */
        tradeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseTradeRes"];
        };
      };
    };
  };
  deleteTrade: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 거래 ID
         * @example 1
         */
        tradeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  updateTrade: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 거래 ID
         * @example 1
         */
        tradeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTradeReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  rejectTradeRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 신청 ID
         * @example 1
         */
        tradeRequestId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  acceptTradeRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 신청 ID
         * @example 1
         */
        tradeRequestId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChangeReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  getVenue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        venueId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVenueRes"];
        };
      };
    };
  };
  getTradeRequests: {
    parameters: {
      query?: {
        /**
         * @description 거래 ID (해당 거래에 대한 신청 목록 조회)
         * @example 1
         */
        tradeId?: number;
        /**
         * @description 신청자 ID (내가 신청한 목록 조회)
         * @example 1
         */
        requesterId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListTradeRequestRes"];
        };
      };
    };
  };
  getTradeRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 신청 ID
         * @example 1
         */
        tradeRequestId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseTradeRequestRes"];
        };
      };
    };
  };
  getMyTickets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListTicketRes"];
        };
      };
    };
  };
  getScheduleSeats: {
    parameters: {
      query?: {
        /**
         * @description 좌석 상태 (AVAILABLE / HOLD / SOLD)
         * @example AVAILABLE
         */
        status?: "AVAILABLE" | "HOLD" | "SOLD";
      };
      header?: never;
      path: {
        /**
         * @description 공연 회차 ID
         * @example 1
         */
        scheduleId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListScheduleSeatViewRes"];
        };
      };
      /** @description 회차 정보 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListScheduleSeatViewRes"];
        };
      };
    };
  };
  getAvailableSeatsForTicketing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 공연 회차 ID
         * @example 1
         */
        scheduleId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListScheduleSeatViewRes"];
        };
      };
      /** @description 회차 정보 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListScheduleSeatViewRes"];
        };
      };
    };
  };
  getReservationDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 예매 ID
         * @example 1
         */
        reservationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationDetailRes"];
        };
      };
      /** @description 본인의 예매가 아님 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationDetailRes"];
        };
      };
      /** @description 예매 정보 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationDetailRes"];
        };
      };
    };
  };
  cancelReservation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 예매 ID
         * @example 1
         */
        reservationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 취소 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
      /** @description 본인의 예매가 아님 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
      /** @description 예매 정보 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
      /** @description 결제 완료된 예매는 취소 불가 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseVoid"];
        };
      };
    };
  };
  getReservation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 예매 ID
         * @example 1
         */
        reservationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationRes"];
        };
      };
      /** @description 본인의 예매가 아님 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationRes"];
        };
      };
      /** @description 예매 정보 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseReservationRes"];
        };
      };
    };
  };
  getMyReservationsDetail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListReservationDetailRes"];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListReservationDetailRes"];
        };
      };
    };
  };
  getMyReservations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListReservationRes"];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListReservationRes"];
        };
      };
    };
  };
  getPerformances: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePagePerformanceListRes"];
        };
      };
    };
  };
  getPerformance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        performanceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePerformanceDetailRes"];
        };
      };
    };
  };
  getSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        performanceId: number;
        scheduleId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePerformanceScheduleDetailRes"];
        };
      };
    };
  };
  getSeatLayout: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 공연 ID
         * @example 1
         */
        performanceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListSectionLayoutRes"];
        };
      };
    };
  };
  searchPerformances: {
    parameters: {
      query: {
        keyword: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponsePagePerformanceListRes"];
        };
      };
    };
  };
  getMyInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseMyInfoRes"];
        };
      };
    };
  };
  getMyLotteryEntry: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListAppliedLotteryInfo"];
        };
      };
    };
  };
  getBankList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseListBankRes"];
        };
      };
    };
  };
  withdrawUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          password: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BaseResponseString"];
        };
      };
    };
  };
}
